{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "flask.fullname" . }}-configmap'
  labels:
    {{- include "flask.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap }}
    {{$key}}: {{ $val | quote}}
    {{- end }}
  {{- end }}